/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.halim.attendance.frames;

import java.awt.Point;
import javax.swing.table.DefaultTableModel;
import org.halim.controller.EmployeeWorkingHoursController;
import org.halim.utils.ModelConverter;
import org.halim.utils.Screen;

/**
 *
 * @author ABDELHALIM
 */
public class HistoryFrame extends javax.swing.JFrame {

    int employee_ID;

    /**
     * Creates new form HistoryFrame
     *
     * @param employee_ID
     */
    public HistoryFrame(int employee_ID) {
        initComponents();
        this.employee_ID = employee_ID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        employeeHistory = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        totalWorkingHours = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        employeeHistory.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        employeeHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Arrival Time", "Depature Time", "Hours", "Minutes", "Seconds"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        employeeHistory.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        employeeHistory.setColumnSelectionAllowed(true);
        employeeHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        employeeHistory.setFillsViewportHeight(true);
        jScrollPane1.setViewportView(employeeHistory);
        employeeHistory.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("Total Working Hours : ");

        totalWorkingHours.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        totalWorkingHours.setText("00 : 00 : 00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(totalWorkingHours)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1116, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(totalWorkingHours))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setLocation(new Point((Screen.getScreenWidth(50) - this.getSize().width / 2),
                (Screen.getScreenHeight(50)) - this.getSize().height / 2));
        DefaultTableModel tableModel = (DefaultTableModel) employeeHistory.getModel();
        tableModel = new ModelConverter().formatDate(
                new EmployeeWorkingHoursController().getEmployeeHistory(employee_ID), tableModel);
        employeeHistory.setModel(tableModel);
        updateWorkingHours();
    }//GEN-LAST:event_formWindowOpened

    private void updateWorkingHours() {
        int hours = 0, minutes = 0, seconds = 0;
        for (int row = 0; row < employeeHistory.getRowCount(); row++) {
            hours += Integer.parseInt("" + employeeHistory.getValueAt(row, 3));
            minutes += Integer.parseInt("" + employeeHistory.getValueAt(row, 4));
            seconds += Integer.parseInt("" + employeeHistory.getValueAt(row, 5));
        }

        if (seconds > 60) {
            minutes += (seconds / 60);
            seconds = (seconds - ((seconds / 60) * 60));
        }

        if (minutes > 60) {
            hours += (minutes / 60);
            minutes = (minutes - ((minutes / 60) * 60));
        }
        totalWorkingHours.setText("" + hours + " : " + minutes + " : " + seconds);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable employeeHistory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel totalWorkingHours;
    // End of variables declaration//GEN-END:variables
}
